CREATE DATABASE IF NOT EXISTS venda;
USE venda;

CREATE TABLE IF NOT EXISTS produtos (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT 1,
    dataDeCadastro DATE NOT NULL,
    dataDeValidade DATE
);